const posts = [
    {
        user_id: 1,
        dp: "../../assets/favicon.png",
        username: 'adfa',
        content: 'dtfcvygbhunjmk',
        image: [],
        timestamp: '06/06/23',
        likes: ['gfd','gdf'],
        comments: [],
        shares: 3,
    },
    {
        user_id: 2,
        dp: "../../assets/favicon.png",
        username: 'adad',
        content: 'exrdctfgbhjnmkcfvgbhjnmk  \n dtcfvgybhnj \n ahdgsgsad \n oahdsnosj',
        image: [],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 4,
    },
    {
        user_id: 3,
        dp: "../../assets/favicon.png",
        username: 'efhdg',
        content: 'fcyvgbhjnmkvgjn \t tcyvgbhjn',
        image: [],
        timestamp: '06/06/23',
        likes: [],
        comments: [],
        shares: 2,
    },
    {
        user_id: 4,
        dp: "../../assets/favicon.png",
        username: 'fsdhb',
        content: 'fcvbhjmkvgbhjnm',
        image: [],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 0,
    },
    {
        user_id: 5,
        dp: "../../assets/favicon.png",
        username: 'sfgdf',
        content: 'dtfyhujoictfvbjnmktfvbhn rxctvbjnmko ytgbujmokvygbhjm',
        image: [],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 69,
    },
    {
        user_id: 6,
        dp: "../../assets/favicon.png",
        username: 'nlkjn',
        content: 'yfvgbhmk ihj',
        image: [],
        timestamp: '06/06/23',
        likes: [],
        comments: [],
        shares: 678,
    },
    {
        user_id: 7,
        dp: "../../assets/favicon.png",
        username: 'iub',
        content: 'tcfvbhjnmk',
        image: [],
        timestamp: '06/06/23',
        likes: [],
        comments: [],
        shares: 1000,
    },
    {
        user_id: 8,
        dp: "../../assets/favicon.png",
        username: 'uygihj',
        content: '',
        image: [require("../../assets/favicon.png"),require("../../assets/favicon.png")],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 10000000,
    },
    {
        user_id: 9,
        dp: "../../assets/favicon.png",
        username: 'uvhbjn',
        content: 'yvgubhjn',
        image: [],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 456789,
    },
    {
        user_id: 10,
        dp: "../../assets/favicon.png",
        username: 'uyvbijn',
        content: 'rdthujl',
        image: [],
        timestamp: '06/06/23',  
        likes: [],
        comments: [],
        shares: 678,
    },
    {
        user_id: 11,
        dp: "../../assets/favicon.png",
        username: 'yvgubhn',
        content: 'tdcfvbhjntcfvgbhjnfcvgbhjnm',
        image: [],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 98765,
    },
    {
        user_id: 12,
        dp: "../../assets/favicon.png",
        username: 'fcvgbhn',
        content: 'fyvgubmk',
        image: [],
        timestamp: '06/06/23', 
        likes: [],
        comments: [],
        shares: 456,
    }
];

export default posts;